language: python
python:
  - 3.8

branches:
  only:
    - main

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

script: pytest
